### ISSUE TITLE
Is this still WIP?

### ISSUE THREAD

**Issue by nikhilRP** [MeteoGroup/grib-library#1]
@erikroijen  and @lajosrodek I am planing on parsing out some grib1 files from ECMWF. 
I see that the library has still WIP in the description. How reliable is it?

PS: This is more of a question than issue. Please create labels for issues, that would help us a lot.
Great work BTW

**Comment by wavermartijn** [comment]
Hi Nikhil,

Yes, it is still work in progress and of course, you could contribute where
necessary for your own needs. Please contact when you have specific
questions.

See you soon,
Martijn
Op 24 jan. 2016 12:40 schreef "Nikhil Reddy" notifications@github.com:

**Comment by nikhilRP** [comment]
Thank you Martijn.
